### ISSUE TITLE
`Change` event not getting triggered.

### ISSUE THREAD

**Issue by warsh33p** [felicegattuso/datedropper#14]
Setting a value through `jQuery.fn.val` does not trigger the `change` event.

This is problematic if you're trying to register an event handler on the input field, since that handler would never get called.

This is actually how I noticed the problem myself. I was using Backbone.js in one of my Projects and wanted to use this datepicker for it. My code promptly stopped working after using this library since the event I was listening to was never getting called.

See my Pull request (https://github.com/felicegattuso/datedropper/pull/13)

**Comment by haydnhkim** [comment]
+1

**Comment by warsh33p** [comment]
Looks like it got fixed with 1075c82abafa8d604c8ecae50cb7493fa56a4d79
