### ISSUE TITLE
d.substr is not a function

### ISSUE THREAD

**Issue by dbhosale** [felicegattuso/datedropper#15]
I was getting error on line no. 655 d.substr(1): d.substr is not a function .

I have made following changes to make it work
line no . 643 
var
                d = day.find('li.dd_sltd_').val(),
                m = month.find('li.dd_sltd_').val(),
                Y = year.find('li.dd_sltd_').val();

//day

			j = d.toString().substr(1), 

//month
			if(m<10) n = m.toString().substr(1); else n = m; 	// 1-12

**Comment by KrownWS** [comment]
Thanks it worked for me too. But now this part of code is on line 990.

Cheers!

**Comment by lenamtl** [comment]
Hi,
What is the complete modification to fix it because I'm having this problem with the latest version.

Thanks
