### ISSUE TITLE
Set the maximum date to today's date

### ISSUE THREAD

**Issue by d3vr** [felicegattuso/datedropper#43]
Hello,

I can't figure out a way to set the max date to today's date. Is there an option or some way to do this ?
Thanks.

**Comment by needim** [comment]
@d3vr There in an option for that
```javascript
{lock: "to"}
```

to: user can't apply future dates
from: user can't apply past dates
false: (default) no limit

**Comment by d3vr** [comment]
Great, thanks for the help @needim !
