### ISSUE TITLE
Dropper Position

### ISSUE THREAD

**Issue by embryologist** [felicegattuso/datedropper#50]
Dear is there a way to modify the position of the dropper, my textbox comes at the end of the page and I would prefer if the dropper shows on top of it instead of going down and scroll for it?

**Comment by felicegattuso** [comment]
Good question,
It is one of the biggest problems people are having.
I hope these days to have the time to add this feature ;)

**Comment by spAnser** [comment]
While awaiting a fix you can try this...

Put this code after initializing the date dropper. This order matters so that the date dropper code runs first so it can remove the dd-bottom class.
```
$('[data-calendar="date"]').on('click', function(e) {
    $('.dd-w').addClass('dd-top').removeClass('dd-bottom');
    var dd_top = $(this).offset().top  - $('.dd-w .dd-c').innerHeight() - 6;
    $('.dd-w .dd-c').css('top', dd_top);
});
```
